[project]
name = "arch-system-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "distro>=1.9.0",
    "mcp[cli]>=1.8.1",
]
